#Requires -Version 5.1
$moduleRoot = Split-Path -Parent $(Split-Path -Parent $PSCommandPath)
. (Join-Path $moduleRoot 'Core\\Logging.ps1')
. (Join-Path $moduleRoot 'Core\\Utilities.ps1')
. (Join-Path $moduleRoot 'Validation\\Prerequisites.ps1')
. (Join-Path $moduleRoot 'Validation\\Parameters.ps1')
. (Join-Path $moduleRoot 'Packaging\\Winget.ps1')
. (Join-Path $moduleRoot 'Packaging\\IntuneWin.ps1')
. (Join-Path $moduleRoot 'Packaging\\Detection.ps1')
. (Join-Path $moduleRoot 'Packaging\\Dialogs.ps1')
. (Join-Path $moduleRoot 'Packaging\\PSADTTemplate.ps1')
. (Join-Path $moduleRoot 'Packaging\\ScriptEditor.ps1')
. (Join-Path $moduleRoot 'Intune\\Upload.ps1')
. (Join-Path $moduleRoot 'GUI\\ConfigureWindow.ps1')
. (Join-Path $moduleRoot 'GUI\\AppDetailsWindow.ps1')
. (Join-Path $moduleRoot 'GUI\\MainWindow.ps1')
